// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@lagertool.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/loans/{id}": {
            "put": {
                "description": "Mark a loan as returned",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Update a loan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Loan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update details",
                        "name": "loan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.UpdateLoan"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/organisations": {
            "get": {
                "description": "Get all organisations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organisations"
                ],
                "summary": "Get all organisations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db_models.Organisation"
                            }
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/buildings": {
            "get": {
                "description": "Get all buildings sorted by update date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "Get all buildings for an organisation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organisation name",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_objects.Building"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new building for an organisation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "buildings"
                ],
                "summary": "Create a new building",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organisation name",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Building object",
                        "name": "building",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.BuildingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db_models.Building"
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/buildings/{buildingId}/rooms": {
            "post": {
                "description": "Create a new room in a building",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Create a new room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organisation name",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Building ID",
                        "name": "buildingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Room object",
                        "name": "room",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.RoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db_models.Room"
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/buildings/{buildingId}/rooms/{roomId}/shelves": {
            "post": {
                "description": "Create a new shelf in a room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shelves"
                ],
                "summary": "Create a new shelf",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organisation name",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Building ID",
                        "name": "buildingId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Shelf object",
                        "name": "shelf",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.ShelfRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db_models.Shelf"
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/inventory": {
            "get": {
                "description": "Get all inventory items sorted by update date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get all inventory items for an organisation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organisation name",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date in format 2006-01-02",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date in format 2006-01-02",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_objects.InventorySorted"
                            }
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/items": {
            "post": {
                "description": "Create a new inventory item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Create a new inventory item",
                "parameters": [
                    {
                        "description": "Inventory item object",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.InventoryItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db_models.Inventory"
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/items/{id}": {
            "get": {
                "description": "Get a specific item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get a specific item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inventory Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date in format 2006-01-02",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in format 2006-01-02",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_objects.InventoryItemWithShelf"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an inventory item's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Update an inventory item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inventory Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update details",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.UpdateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db_models.Inventory"
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/items/{id}/borrows": {
            "get": {
                "description": "Get all borrow/loan history for an inventory item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get borrow history for an item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inventory Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_objects.BorrowHistory"
                            }
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/rooms": {
            "get": {
                "description": "Get all rooms sorted by update date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Get all rooms for an organisation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organisation name",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_objects.Room"
                            }
                        }
                    }
                }
            }
        },
        "/organisations/{orgId}/shelves": {
            "get": {
                "description": "Get all shelves for an organisation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shelves"
                ],
                "summary": "Get all shelves for an organisation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organisation name",
                        "name": "orgId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_objects.Shelves"
                            }
                        }
                    }
                }
            }
        },
        "/requests/{id}": {
            "put": {
                "description": "Update the status of a request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Update a request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/requests/{id}/loans": {
            "put": {
                "description": "Mark all loans for a given request as returned",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Bulk update loans for a request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update details",
                        "name": "loan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.UpdateLoan"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/requests/{id}/messages": {
            "get": {
                "description": "Get all messages (user and admin) for a request, sorted by timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Get messages for a request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_objects.Message"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Post a user message on a borrow request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Post a message to a request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message object",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.UserMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_objects.UserMessage"
                        }
                    }
                }
            }
        },
        "/requests/{id}/review": {
            "post": {
                "description": "Review/approve/deny a borrow request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Review a request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review details",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.RequestReview"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db_models.RequestReview"
                        }
                    }
                }
            }
        },
        "/search/{searchTerm}": {
            "get": {
                "description": "Search for inventory items by name using fuzzy matching",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Fuzzy search for inventory items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "searchTerm",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db_models.Inventory"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/cart": {
            "get": {
                "description": "Get a user's shopping cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Get a user's shopping cart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date in format 2006-01-02",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date in format 2006-01-02",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/api_objects.CartItem"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/cart/checkout": {
            "post": {
                "description": "Checkout the user's shopping cart and create requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Checkout shopping cart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Checkout details",
                        "name": "checkout",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.CheckoutRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/users/{userId}/cart/items": {
            "post": {
                "description": "Add an item to the shopping cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Add an item to the shopping cart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cart item object",
                        "name": "cart_item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.CartRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db_models.ShoppingCartItem"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete all items from a user's shopping cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Delete all cart items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db_models.ShoppingCartItem"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/cart/items/{itemId}": {
            "put": {
                "description": "Update the amount of an item in a user's shopping cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Update a cart item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Inventory Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update details",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_objects.UpdateCartItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Delete a specific item from a user's shopping cart by inventory item ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Delete a single cart item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Inventory Item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "api_objects.BorrowHistory": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "approvalState": {
                    "type": "string"
                },
                "approvalStateTime": {
                    "type": "string"
                },
                "authorName": {
                    "type": "string"
                },
                "dueAt": {
                    "type": "string"
                },
                "returnedAt": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "api_objects.Building": {
            "type": "object",
            "properties": {
                "campus": {
                    "description": "GPS        string   ` + "`" + `json:\"gps\"` + "`" + `",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updateDate": {
                    "type": "string"
                }
            }
        },
        "api_objects.BuildingRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "campus": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api_objects.CartItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "amountSelected": {
                    "type": "integer"
                },
                "available": {
                    "type": "integer"
                },
                "building": {
                    "$ref": "#/definitions/db_models.Building"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "room": {
                    "$ref": "#/definitions/db_models.Room"
                },
                "shelfId": {
                    "type": "string"
                }
            }
        },
        "api_objects.CartRequest": {
            "type": "object",
            "required": [
                "id",
                "numSelected"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "numSelected": {
                    "type": "integer"
                }
            }
        },
        "api_objects.CheckoutRequest": {
            "type": "object",
            "required": [
                "endDate",
                "startDate"
            ],
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                }
            }
        },
        "api_objects.ColumnElementRequest": {
            "type": "object",
            "required": [
                "elements",
                "id"
            ],
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_objects.ShelfElementRequest"
                    }
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "api_objects.Columns": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_objects.Element"
                    }
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "api_objects.Element": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api_objects.InventoryItemRequest": {
            "type": "object",
            "required": [
                "amount",
                "isConsumable",
                "name",
                "note",
                "shelfId",
                "shelfUnitId"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "isConsumable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "organisation": {
                    "type": "string"
                },
                "shelfId": {
                    "type": "string"
                },
                "shelfUnitId": {
                    "type": "string"
                }
            }
        },
        "api_objects.InventoryItemWithShelf": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "available": {
                    "type": "integer"
                },
                "building": {
                    "$ref": "#/definitions/db_models.Building"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "room": {
                    "$ref": "#/definitions/db_models.Room"
                },
                "shelf": {
                    "$ref": "#/definitions/api_objects.Shelves"
                },
                "shelfId": {
                    "type": "string"
                }
            }
        },
        "api_objects.InventorySorted": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "available": {
                    "type": "integer"
                },
                "building": {
                    "$ref": "#/definitions/db_models.Building"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "room": {
                    "$ref": "#/definitions/db_models.Room"
                }
            }
        },
        "api_objects.Message": {
            "type": "object",
            "properties": {
                "authorName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "timeStamp": {
                    "type": "string"
                }
            }
        },
        "api_objects.RequestReview": {
            "type": "object",
            "properties": {
                "note": {
                    "type": "string"
                },
                "outcome": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api_objects.Room": {
            "type": "object",
            "properties": {
                "building": {
                    "$ref": "#/definitions/db_models.Building"
                },
                "floor": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "updateDate": {
                    "type": "string"
                }
            }
        },
        "api_objects.RoomRequest": {
            "type": "object",
            "required": [
                "floor",
                "number"
            ],
            "properties": {
                "floor": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                }
            }
        },
        "api_objects.ShelfElementRequest": {
            "type": "object",
            "required": [
                "id",
                "type"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api_objects.ShelfRequest": {
            "type": "object",
            "required": [
                "columns",
                "id",
                "name"
            ],
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_objects.ColumnElementRequest"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api_objects.Shelves": {
            "type": "object",
            "properties": {
                "building": {
                    "$ref": "#/definitions/db_models.Building"
                },
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_objects.Columns"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "room": {
                    "$ref": "#/definitions/db_models.Room"
                }
            }
        },
        "api_objects.UpdateCartItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                }
            }
        },
        "api_objects.UpdateItemRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "shelfUnitId": {
                    "type": "string"
                }
            }
        },
        "api_objects.UpdateLoan": {
            "type": "object",
            "properties": {
                "returnedAt": {
                    "type": "string"
                }
            }
        },
        "api_objects.UpdateRequest": {
            "type": "object",
            "properties": {
                "outcome": {
                    "type": "string"
                }
            }
        },
        "api_objects.UserMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "db_models.Building": {
            "type": "object",
            "properties": {
                "campus": {
                    "type": "string"
                },
                "gps": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "db_models.Column": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "shelf": {
                    "$ref": "#/definitions/db_models.Shelf"
                },
                "shelf_id": {
                    "type": "string"
                },
                "shelf_units": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db_models.ShelfUnit"
                    }
                }
            }
        },
        "db_models.Inventory": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_consumable": {
                    "type": "boolean"
                },
                "item_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "request_item": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db_models.RequestItems"
                    }
                },
                "shelf": {
                    "$ref": "#/definitions/db_models.Shelf"
                },
                "shelf_id": {
                    "type": "string"
                },
                "shelf_unit": {
                    "$ref": "#/definitions/db_models.ShelfUnit"
                },
                "shelf_unit_id": {
                    "type": "string"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "db_models.Organisation": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "db_models.Request": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "organisation": {
                    "$ref": "#/definitions/db_models.Organisation"
                },
                "organisationName": {
                    "type": "string"
                },
                "request_item": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db_models.RequestItems"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "time_state": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/db_models.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "db_models.RequestItems": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "inventory": {
                    "$ref": "#/definitions/db_models.Inventory"
                },
                "inventory_id": {
                    "type": "integer"
                },
                "request": {
                    "$ref": "#/definitions/db_models.Request"
                },
                "request_id": {
                    "type": "integer"
                }
            }
        },
        "db_models.RequestReview": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "outcome": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/db_models.Request"
                },
                "request_id": {
                    "type": "integer"
                },
                "time_stamp": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/db_models.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "db_models.Room": {
            "type": "object",
            "properties": {
                "building": {
                    "$ref": "#/definitions/db_models.Building"
                },
                "building_id": {
                    "type": "integer"
                },
                "floor": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "db_models.Shelf": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db_models.Column"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organisation": {
                    "$ref": "#/definitions/db_models.Organisation"
                },
                "owned_by": {
                    "type": "string"
                },
                "room": {
                    "$ref": "#/definitions/db_models.Room"
                },
                "room_id": {
                    "type": "integer"
                },
                "update_date": {
                    "type": "string"
                }
            }
        },
        "db_models.ShelfUnit": {
            "type": "object",
            "properties": {
                "column": {
                    "$ref": "#/definitions/db_models.Column"
                },
                "column_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "position_in_column": {
                    "description": "to change the order of the units in the column later",
                    "type": "integer"
                },
                "type": {
                    "description": "0 is small, 1 is big",
                    "type": "integer"
                }
            }
        },
        "db_models.ShoppingCart": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "shopping_cart_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db_models.ShoppingCartItem"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "db_models.ShoppingCartItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "inventory": {
                    "$ref": "#/definitions/db_models.Inventory"
                },
                "inventory_id": {
                    "type": "integer"
                },
                "shopping_cart": {
                    "$ref": "#/definitions/db_models.ShoppingCart"
                },
                "shopping_cart_id": {
                    "type": "integer"
                }
            }
        },
        "db_models.User": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "issuer": {
                    "type": "string"
                },
                "last_login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Lagertool Inventory API",
	Description:      "Backend API for inventory management system tracking items, locations, and loans",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
